version: '3'

services:
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
      
  eventstore:
    image: eventstore/eventstore:release-5.0.1
    container_name: eventstore
    ports:
      - 2113:2113
      - 1113:1113
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=TRUE
      
  snapshot_store:
    image: mongo:latest
    ports:
      - 27017:27017
      
  readstore:
    image: postgres:10.6-alpine
    container_name: readstore
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
    command:
      - -c
      - max_prepared_transactions=100
    ports:
      - "5433:5432"

