server:
  port: 8090
## default connection pool
spring:
  jpa:
    properties:
      hibernate:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5433/productdb?currentSchema=product
    username: productadmin
    password: admin#3012
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 1.5
          max-interval: 5000

amqp:
  queue: product.query.events
  dlx:
    queue: product.query.events.dlx

axon:
  serializer:
    general: jackson
  eventhandling:
      processors:
        amqpEvents:
          source: inputMessageSource
          mode: subscribing

security:
  access:
    api:
      permissions-uri: http://localhost:5000/totvs.rac/api/permissions
  oauth2:
    resource:
      id: 'authorization_api'
      jwk:
        key-set-uri: http://localhost:5000/totvs.rac/.well-known/openid-configuration/jwks