spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    jdbcUrl: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}