spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    listener:
      concurrent-consumers: 1
      max-concurrent-consumers: 1
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

product:
  service:
    protocol: ${SERVICE_PROTOCOL}
    host: ${SERVICE_HOST}
    port: ${SERVICE_PORT}

amqp:
  exchange: product.events
  queue: test.product.events